---
# Source: x-gatekeeper/charts/application/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:  
  labels:
    app: x-gatekeeper
    helm.sh/chart: application-1.0.0
  name: x-gatekeeper
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: x-gatekeeper
---
# Source: x-gatekeeper/charts/application/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:  
  labels:
    app: x-gatekeeper
    helm.sh/chart: application-1.0.0
  name: x-gatekeeper-env-vars
data:
  CORS_ALLOWED_ORIGINS: momofamily.tplinkdns.com
  HTTP_PORT: "8080"
  XWORD_ADDR: x-word.application.svc.cluster.local:443
---
# Source: x-gatekeeper/charts/application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:    
  labels:
    app: x-gatekeeper
    helm.sh/chart: application-1.0.0
  name: x-gatekeeper
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
    - name: x-gatekeeper
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: x-gatekeeper
---
# Source: x-gatekeeper/charts/application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:  
  annotations:
    eloader.stakater.com/auto: "true"  
  labels:
    app: x-gatekeeper
    helm.sh/chart: application-1.0.0
  name: x-gatekeeper

spec:
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: x-gatekeeper
  template:
    metadata:      
      labels:
        app: x-gatekeeper
    spec:
      containers:
        - name: x-gatekeeper
          image: ghcr.io/hungp29/x-gatekeeper:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: x-gatekeeper-env-vars
              prefix: GATEKEEPER_
          livenessProbe:
            failureThreshold: 3
            grpc:
              port: 8080
              service: ""
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            grpc:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            grpc:
              port: 8080
              service: ""
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      terminationGracePeriodSeconds: 30
---
# Source: x-gatekeeper/charts/application/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:  
  labels:
    app: x-gatekeeper
    helm.sh/chart: application-1.0.0
  name: x-gatekeeper
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      - periodSeconds: 15
        type: Pods
        value: 4
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 4
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: x-gatekeeper
---
# Source: x-gatekeeper/charts/application/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:  
  labels:
    app: x-gatekeeper
    helm.sh/chart: application-1.0.0
  name: x-gatekeeper
spec:
  ingressClassName: nginx
  rules:
    - host: momofamily.tplinkdns.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: x-gatekeeper
                port:
                  number: 80
  tls:
    - hosts:
      - momofamily.tplinkdns.com
      secretName: x-gatekeeper-tls
