apiVersion: v2
name: x-gatekeeper
description: x-gatekeeper HTTP service (Gin)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - x-gatekeeper
  - gin
dependencies:
  - name: go-application
    alias: application
    version: 1.0.0
    repository: oci://ghcr.io/hungp29/charts
maintainers:
  - name: Hung Pham
    email: dev.hungpham@gmail.com
    url: https://github.com/hungp29
