# Application configuration
application:
  deployment:
    container:
      image:
        repository: hungp29/x-gatekeeper
        tag: latest
      envFrom:
        - configMapRef:
            name: x-gatekeeper-env-vars
          prefix: "GATEKEEPER_"
  
  service:
    port: 80
  
  ingress:
    enabled: true
    host: momofamily.tplinkdns.com
    paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
    tls: true
    tlsSecretName: x-gatekeeper-tls