# Application configuration
application:
  deployment:
    container:
      image:
        repository: hungp29/x-gatekeeper
        tag: latest
      envFrom:
        - configMapRef:
            name: x-gatekeeper-env-vars
          prefix: "GATEKEEPER_"
      startupProbe:
        failureThreshold: 30
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1

      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1

      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
  
  service:
    port: 80
  
  ingress:
    enabled: true
    host: momofamily.tplinkdns.com
    paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
    tls: true
    tlsSecretName: x-gatekeeper-tls