name: 'Production'

on:
  release:
    types:
      - released
  # workflow_dispatch:

jobs:
  production-deployment:
    permissions:
      contents: read
      packages: write
    uses: hungp29/x-actions/.github/workflows/go-production.yaml@v1.0.2
    secrets: inherit
